# Generated by Django 3.2.2 on 2021-05-07 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('ticker', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('isin_code', models.CharField(max_length=255, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('exchange', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'default_related_name': 'stock',
            },
        ),
        migrations.CreateModel(
            name='SharesInfo',
            fields=[
                ('stock_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='sharesInfo', serialize=False, to='dashboard.stock')),
                ('total_shares', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('avg_price', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                'default_related_name': 'sharesInfo',
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('is_buy', models.BooleanField(default=False)),
                ('txn_date', models.DateField()),
                ('shares', models.DecimalField(decimal_places=4, max_digits=10)),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trade', to='dashboard.stock')),
            ],
            options={
                'default_related_name': 'trade',
            },
        ),
    ]
